### ISSUE TITLE
v2版本的商户转账到用户零钱接口微信官方以及修改了

### ISSUE THREAD

**Issue by JianJiaPHP** [yansongda/laravel-pay#100]
![KSZQI0{ DVT8%WRK9OC581J](https://github.com/yansongda/laravel-pay/assets/43328671/a1285e7a-861c-4492-a40b-24b0acff0281)

**Comment by yansongda** [comment]
麻烦提供下 微信的文档地址

**Comment by JianJiaPHP** [comment]
https://pay.weixin.qq.com/docs/merchant/apis/batch-transfer-to-balance/transfer-batch/initiate-batch-transfer.html

**Comment by JianJiaPHP** [comment]
现在的转账方法是走的mmpaymkttransfers/promotion/transfers这个接口 而这个接口以及被微信官方认定为企业商户转账到用户零钱 并且不可申请开通

**Comment by yansongda** [comment]
帮忙去 [yansongda/pay](https://github.com/yansongda/pay/) 里提个 issue，我抽时间吧这个功能加上

**Comment by JianJiaPHP** [comment]
ok
