### ISSUE TITLE
商家转账到零钱小程序跟公众号错误

### ISSUE THREAD

**Issue by leifen** [yansongda/laravel-pay#101]
商家转账到零钱小程序与公众号无法自行判断用户来源
mp_app_id、mini_app_id需要手动判断

**Comment by yansongda** [comment]
可以传参 `['_type' => 'mp/mini']` sdk 就会自动判断了

**Comment by yansongda** [comment]
https://github.com/yansongda/pay/blob/c3ddfb28657560a659ffc22f1ebc6ccb6f490311/src/Plugin/Wechat/GeneralPlugin.php#L78
