### ISSUE TITLE
冲突

### ISSUE THREAD

**Issue by mathuse** [yansongda/laravel-pay#107]
已经使用php7.3开发了很久，这个库却要求php8,怎么解决？升级php版本岂不导致很多冲突

**Comment by yansongda** [comment]
你可以选择继续使用老版本

**Comment by mathuse** [comment]
我现在用php7.3最高安装yansongda/pay3.0&nbsp; 实用方法和更高版本的pay有什么不同吗

&nbsp;


??
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年10月24日(星期二) 晚上9:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yansongda/laravel-pay] 冲突 (Issue #107)





 
你可以选择继续使用老版本

**Comment by yansongda** [comment]
更高版本支持的功能更多，具体可见 [CHANGELOG](https://github.com/yansongda/pay/blob/master/CHANGELOG.md)
