### ISSUE TITLE
laravel 11 中貌似无法正常使用?

### ISSUE THREAD

**Issue by slowlyo** [yansongda/laravel-pay#112]
### 环境:

- php 8.3
- laravel 11.0
- laravel-pay 3.7

### 代码: 

```php
$result = Pay::wechat()->mini([
    'out_trade_no' => time() . 'a',
    'body'         => 'subject-测试',
    'total_fee'    => 1,
    'openid'       => 'ou3nG5S6gA_9uHTSEbbXg76mI4iQ',
]);

```

### 这段代码得到以下错误:

`容器未找到: getContainer() 方法调用失败! 或许你应该先 setContainer()`

尝试传入config `Pay::wechat(config('pay'))`

### 得到新的错误

`微信返回状态码异常，请检查参数是否错误`

- 找到抛出异常处, 打印 `$rocket->getDestination()`

![image](https://github.com/yansongda/laravel-pay/assets/94038215/49f3d408-848d-423e-9b00-f09fbdb99c54)

**Comment by yansongda** [comment]
> 容器未找到: getContainer() 方法调用失败! 或许你应该先 setContainer()

1、使用 laravel 的 facade 即 `use Pay;`
或 2、先执行 Pay::config()

> 微信返回状态码异常，请检查参数是否错误

仔细看文档，按文档处理

**Comment by slowlyo** [comment]
> > 容器未找到: getContainer() 方法调用失败! 或许你应该先 setContainer()
> 
> 1、使用 laravel 的 facade 即 `use Pay;` 或 2、先执行 Pay::config()
> 
> > 微信返回状态码异常，请检查参数是否错误
> 
> 仔细看文档，按文档处理


调用的代码跟实例代码完全一致, 配置中, 必填项均已填写, 依然得到错误

`微信返回状态码异常，请检查参数是否错误`

应该从哪方面排查?

**Comment by slowlyo** [comment]
找到原因了   调的 v3 的接口, 参数有差异..
