### ISSUE TITLE
自定义中间件函数报错， header function not found

### ISSUE THREAD

**Issue by cielu** [yansongda/laravel-pay#13]
public function handle($request, Closure $next)
    {
        $response = $next($request);
        # if the app env isn't production
        if(config('app.env') !== 'production'){
            $response->header('Access-Control-Allow-Origin', '*');
            $response->header('Access-Control-Allow-Headers', 'Origin, X-Requested-With, Cookie, Content-Type, Accept, Authorization');
            $response->header('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE');
            $response->header('Access-Control-Allow-Credentials', 'false');
        }
        return $response;
    }

header不存在。。。

**Comment by yansongda** [comment]
麻烦尝试使用最新 v3 版

感谢支持
