### ISSUE TITLE
Get Wechat API Error:参数错误：appid字段必填，最长为32个字符

### ISSUE THREAD

**Issue by chensongah** [yansongda/laravel-pay#15]
业务描述：

1. app用户提现，使用的是app调用微信返回的OpenID，不是web端调用微信公众号返回的OpenID。
2. 商户 企业付款给用户零钱

实例化时使用的配置如下：
```
$data = [
    'app_id' => config('pay.wechat.app_id'),
    'appid' => config('pay.wechat.appid'),
    'mch_id' => config('pay.wechat.mch_id'),
    'notify_url' => config('pay.wechat.notify_url'),
    'key' => config('pay.wechat.key'),
    'cert_client' => config('pay.wechat.cert_client'),
    'cert_key' => config('pay.wechat.cert_key')
];
```

调用 transfer 方法 ， 企业付款给用户零钱，如下：
```
public function transfer($partner_trade_no = '', $open_id = '', $amount = 0, $desc = '', $type = '')
{
$order = [
    'partner_trade_no' => $partner_trade_no, //商户订单号
    'openid' => $open_id,                    //收款人的openid
    'check_name' => 'NO_CHECK',              //NO_CHECK：不校验真实姓名\FORCE_CHECK：强校验真实姓名
//            're_user_name' => '张三',              //check_name为 FORCE_CHECK 校验实名的时候必须提交
    'amount' => $amount,                     //企业付款金额，单位为分
    'desc' => $desc,                         //付款说明
];
if ($type) $order['type'] = $type;

return $this->wechat->transfer($order);
```

发现问题（重点）：
当追踪代码时，文件：vendor/yansongda/pay/src/Gateways/Wechat/TransferGateway.php,会发现
```
public function pay($endpoint, array $payload): Collection
{
    if ($this->mode === Wechat::MODE_SERVICE) {
        unset($payload['sub_mch_id'], $payload['sub_appid']);
    }
//        $type = isset($payload['type']) ? ($payload['type'].($payload['type'] == 'app' ?: '_').'id') : 'app_id';
    $type = isset($payload['type']) && $payload['type'] == 'app' ? $payload['type'] . 'id' : 'app_id';

    $payload['mch_appid'] = $this->config->get($type, '');
    $payload['mchid'] = $payload['mch_id'];
    php_sapi_name() === 'cli' ?: $payload['spbill_create_ip'] = Request::createFromGlobals()->server->get('SERVER_ADDR');

    unset($payload['appid'], $payload['mch_id'], $payload['trade_type'],
        $payload['notify_url'], $payload['type']);

    $payload['sign'] = Support::generateSign($payload, $this->config->get('key'));

    Log::debug('Paying A Transfer Order:', [$endpoint, $payload]);

    return Support::requestApi(
        'mmpaymkttransfers/promotion/transfers',
        $payload,
        $this->config->get('key'),
        $this->config->get('cert_client'),
        $this->config->get('cert_key')
    );
}
```

1. 其中的$type 变量获取到的是 “app1id”，报“Get Wechat API Error:参数错误：appid字段必填，最长为32个字符”，是错误的，$type应该返回 “appid”
2. 把``` $type = isset($payload['type']) ? ($payload['type'].($payload['type'] == 'app' ?: '_').'id') : 'app_id';```
改成 ``` $type = isset($payload['type']) && $payload['type'] == 'app' ? $payload['type'].'id' : 'app_id'; ```
修改后程序方能获取到 APP 引用的 appid，才能企业付款成功

<h3>望作者能够重视，说错的地方请指出，谢谢，盼复</h3>

**Comment by yansongda** [comment]
当时在扣上特定和您说了，让您 composer update ，为什么不执行？

**Comment by chensongah** [comment]
目前的包版本如下：
1. yansongda/laravel-pay --> version: v2.0.1
2. yansongda/pay --> version: v2.1.2

> 根据 packagist.org 关于页面上的 Update Schedule 规则说明：packagist.org 会对新提交的 package 立即抓取一次。已经提交的 package 一般是每周抓取一次更新

composer update的目的是更新包，我的项目不能全局执行composer update，有些包不能更新，你可以说下我需要更新哪些包，我单独处理.
所以，你让我composer update解决不了问题，有缓存，更新不了版本

**Comment by yansongda** [comment]
yansongda/pay --> version: v2.1.2

**Comment by chensongah** [comment]
我目前用的就是这两个版本
yansongda/laravel-pay 是：version: v2.0.1
yansongda/pay是：version: v2.1.2
就是我上面第一条issue里提交：

1. 其中的$type 变量获取到的是 “app1id”，报“Get Wechat API Error:参数错误：appid字段必填，最长为32个字符”，是错误的，$type应该返回 “appid”
2. `$type = isset($payload['type']) ? ($payload['type'].($payload['type'] == 'app' ?: '_').'id') : 'app_id';`
改成 `$type = isset($payload['type']) && $payload['type'] == 'app' ? $payload['type'].'id' : 'app_id';`
后，$type返回 “appid”才行，而不是返回‘app1id’
3. 修改后程序方能获取到 APP 引用的 appid，才能企业付款成功

**Comment by yansongda** [comment]
大哥，我都说了让您 update pay 这个包。。。。。。。。。。。
