### ISSUE TITLE
验签失败

### ISSUE THREAD

**Issue by cdhraesaemer** [yansongda/laravel-pay#16]
验签失败
支付宝app支付接口
返回值为如图
![default](https://user-images.githubusercontent.com/3795018/43355698-8df8ad52-9293-11e8-945c-229550ed56b0.png)

![default](https://user-images.githubusercontent.com/3795018/43355733-f842b766-9293-11e8-90e6-d4a1bb24061a.png)

**Comment by yansongda** [comment]
请参考文档 FAQ 先进行自查。如有问题，请去 pay 包，按照 ISSUE 模板提。

谢谢
