### ISSUE TITLE
支付宝支付成功，但在查询订单时出错，请问是什么原因？

### ISSUE THREAD

**Issue by youl123** [yansongda/laravel-pay#17]
$order = [
            'out_trade_no' => '201808071545335463',
            'bill_type' => 'trade'
        ];
        $alipay = Pay::alipay();
        return $alipay->find($order);
这个商户订单是支付成功了的。
错误提示：
ErrorException: openssl_verify(): supplied key param cannot be coerced into a public key in file /data/zyzxpay/vendor/yansongda/pay/src/Gateways/Alipay/Support.php on line 157

请教大侠，如何解决。谢谢！

**Comment by yansongda** [comment]
错误提示很清楚了。

**Comment by youl123** [comment]
非常感谢你能回复。
