### ISSUE TITLE
H5支付 ajax调用 返回的结果如何取到跳转地址

### ISSUE THREAD

**Issue by binxyz** [yansongda/laravel-pay#20]
RedirectResponse {#518
  #targetUrl: "https://wx.tenpay.com/cgi-bin/mmpayweb-bin/checkmweb?prepay_id=wx111649337720935c6a28bec83268885069&package=199169225"
  +headers: ResponseHeaderBag {#519
    #computedCacheControl: array:2 [
      "no-cache" => true
      "private" => true
    ]
    #cookies: []
    #headerNames: array:3 [
      "cache-control" => "Cache-Control"
      "date" => "Date"
      "location" => "Location"
    ]
    #headers: array:3 [
      "cache-control" => array:1 [
        0 => "no-cache, private"
      ]
      "date" => array:1 [
        0 => "Thu, 11 Oct 2018 08:49:33 GMT"
      ]
      "location" => array:1 [
        0 => "https://wx.tenpay.com/cgi-bin/mmpayweb-bin/checkmweb?prepay_id=wx111649337720935c6a28bec83268885069&package=199169225"
      ]
    ]
    #cacheControl: []
  }
  #content: """
    <!DOCTYPE html>\n
    <html>\n
        <head>\n
            <meta charset="UTF-8" />\n
            <meta http-equiv="refresh" content="0;url=https://wx.tenpay.com/cgi-bin/mmpayweb-bin/checkmweb?prepay_id=wx111649337720935c6a28bec83268885069&amp;package=199169225" />\n
    \n
            <title>Redirecting to https://wx.tenpay.com/cgi-bin/mmpayweb-bin/checkmweb?prepay_id=wx111649337720935c6a28bec83268885069&amp;package=199169225</title>\n
        </head>\n
        <body>\n
            Redirecting to <a href="https://wx.tenpay.com/cgi-bin/mmpayweb-bin/checkmweb?prepay_id=wx111649337720935c6a28bec83268885069&amp;package=199169225">https://wx.tenpay.com/cgi-bin/mmpayweb-bin/checkmweb?prepay_id=wx111649337720935c6a28bec83268885069&amp;package=199169225</a>.\n
        </body>\n
    </html>
    """
  #version: "1.0"
  #statusCode: 302
  #statusText: "Found"
  #charset: null
}

**Comment by shenglin-php** [comment]
同问

**Comment by yansongda** [comment]
文档。谢谢
