### ISSUE TITLE
只是加了一个provider嘛？

### ISSUE THREAD

**Issue by reatang** [yansongda/laravel-pay#21]
1、暴露的api呀
2、callback
3、event
4、数据库记录

甚至：
一个默认的订单支付页面

在未来有没有这个计划？

**Comment by yansongda** [comment]
最新版本已经支持 **事件系统**，欢迎体验

**Comment by zoulux** [comment]
事件系统 我在laravel中接收不到 
` Events::addListener(Events::PAY_STARTED, [new PayStartingListener(), 'sendEmail']);
class PayStartingListener
{
    public function sendEmail(PayStarted $event)
    {
        \Log::info('0------' . json_encode($event->params));
    }
}


`
