### ISSUE TITLE
微信支付成功之后回调如何返回给微信失败信息。

### ISSUE THREAD

**Issue by dongkaipo** [yansongda/laravel-pay#23]
以前我这边出现业务问题，会给微信返回错误，然后微信继续进行回调，现在怎么处理这个，我看代码里只能返回 success，
```
return $pay->success();
```
这个返回建议添加一个失败的方法。

**Comment by yansongda** [comment]
如果失败，不需要返回任何信息（或随便返回一些字符串），微信支付会认定通知失败，继续重试通知的。

感谢支持！
