### ISSUE TITLE
英文错误：微信小程序 不是 WECHAT MINIAPP

### ISSUE THREAD

**Issue by sinkcup** [yansongda/laravel-pay#27]
微信小程序 不是 WECHAT MINIAPP，而是 WeChat Mini Program，把微信切换到英文版即可看到官方翻译，或者查看微信官方英文文档：https://open.wechat.com/cgi-bin/newreadtemplate?t=overseas_open/docs/mini-programs/development/brief-tutorial#development_brief-tutorial

**Comment by sinkcup** [comment]
纠正了吗？

**Comment by yansongda** [comment]
最新 v3 版已统一为 mini

欢迎体验
