### ISSUE TITLE
配置文件 vendor:publish

### ISSUE THREAD

**Issue by fxxxf** [yansongda/laravel-pay#3]
`$ php artisan vendor:publish --provider="Yansongda\\LaravelPay\\PayServiceProvider" --tag=config`

应改为

`$ php artisan vendor:publish --provider="Yansongda\LaravelPay\PayServiceProvider" --tag=config`

**Comment by yansongda** [comment]
您好，感谢关注。

这种写法是可以的，您可以自行测试看看。

感谢您的支持！
