### ISSUE TITLE
支付宝查询订单失败

### ISSUE THREAD

**Issue by ugarden** [yansongda/laravel-pay#32]
使用代码Pay::alipay(config('pay.alipay'))->find($number)报ErrorException: call_user_func() expects parameter 1 to be a valid callback, non-static method Yansongda\Pay\Gateways\Alipay\WapGateway::find()请问是什么原因用的版本是v2.0和v2.2都不行

**Comment by yansongda** [comment]
https://github.com/yansongda/pay/issues/226
