### ISSUE TITLE
关于配置的问题

### ISSUE THREAD

**Issue by MukuroSama** [yansongda/laravel-pay#33]
我一直以为这个包可以默认配一份配置，然后在调用的时候能临时传参，覆盖部分配置（也可以不传，就用默认的）
结果看了半天源码，不知道我理解的对不对——
yansongda/pay这个包不含有默认配置的功能，必须调用的时候手动传配置参数。
yansongda/laravel-pay这个包只是把上面那个包调用了一下，并且默认读取laravel的配置，传入上面那个包里，相当于免去了手动传配置参数，并提供了一个定死的配置方法，反而把配置的灵活性搞没了。
而我一开始以为的，既有默认配置，又可以手动传参覆盖部分默认配置的特性，一开始就不存在？
所以这个laravel包只适用于只有一个支付帐号、一套参数的情况下，如果系统里包含多个支付帐号，想要灵活使用不同的帐号，则必须使用yansongda/pay才行，对不对？

**Comment by wuliangpro** [comment]
我也发现了，这个设定有点诡异啊，return_url不支持动态设置，我怎么判断订单。。。

**Comment by yansongda** [comment]
多账户情况请使用 yansongda/pay

感谢支持

**Comment by datangkang123** [comment]
确实发现了这问题，支付后跳转地址，不支持动态设置。
