### ISSUE TITLE
Undefined class constant 'SIGN_FAILED'

### ISSUE THREAD

**Issue by jcsofts** [yansongda/laravel-pay#35]
沙盒环境，调用scan 方法，验证签名失败
$result=Pay::alipay(config('pay.alipay'))->scan([
                'id'=>$order->id,
                'out_trade_no'=>$order->order_no,
                'total_amount'=>$order->final_amount,
                'subject'=>$order->name
            ]);

得到下边错误
 "message": "Undefined class constant 'SIGN_FAILED'",
    "exception": "Symfony\\Component\\Debug\\Exception\\FatalThrowableError",
    "file": "/var/www/html/vendor/yansongda/pay/src/Gateways/Alipay/Support.php",
    "line": 336,
    "trace": [
        {
            "file": "/var/www/html/vendor/yansongda/pay/src/Gateways/Alipay/Support.php",
            "line": 138,
            "function": "processingApiResult",
            "class": "Yansongda\\Pay\\Gateways\\Alipay\\Support",
            "type": "::"
        },

**Comment by yansongda** [comment]
麻烦 composer update 到最新版

感谢支持

**Comment by jcsofts** [comment]
Sorry, 不好意思，配置错了，api_public_key应该是支付宝公钥，填成应用公钥了。
