### ISSUE TITLE
 Alipay Sign Verify FAILED

### ISSUE THREAD

**Issue by liujiacong** [yansongda/laravel-pay#37]
Alipay Sign Verify FAILED
退款能成功，但是一直显示签名失败

**Comment by neatstudio** [comment]
同上。我是支付后收入的推送。验签失败

**Comment by puzzle9** [comment]
https://github.com/yansongda/pay/issues/375#issuecomment-682509770

**Comment by yansongda** [comment]
麻烦尝试使用最新 v3 版

感谢支持
