### ISSUE TITLE
IOS下支付宝H5支付后无法跳回到网页上去

### ISSUE THREAD

**Issue by asundust** [yansongda/laravel-pay#38]
IOS12iPhone用safari发起的支付宝支付，唤起支付宝APP，支付成功后直接进入支付宝的首页（就是打开支付宝app的默认页面），没有跳转回到safari浏览器。传入的参数有`no`,`amount`,`name`,`passback_params`。
使用的版本为
yansongda/laravel-pay                 v2.0.2
yansongda/pay                         v2.8.2

**Comment by datangkang123** [comment]
微信的H5支付也是无法返回。

**Comment by asundust** [comment]
安卓浏览器是能跳回的吗？
