### ISSUE TITLE
请问官方有文档吗？

### ISSUE THREAD

**Issue by RouyiTian** [yansongda/laravel-pay#39]

**Comment by yansongda** [comment]
请参考 https://github.com/yansongda/pay

**Comment by RouyiTian** [comment]
收到，谢谢！




------------------ 原始邮件 ------------------
发件人: "yansongda"<notifications@github.com>; 
发送时间: 2019年7月21日(星期天) 下午5:30
收件人: "yansongda/laravel-pay"<laravel-pay@noreply.github.com>; 
抄送: "东方郁闷"<2428787575@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [yansongda/laravel-pay] 请问官方有文档吗？ (#39)




请参考 https://github.com/yansongda/pay
 
&mdash;
