### ISSUE TITLE
微信回调在部分情况下有异常..Convert To Array Error! Invalid Xml! 

### ISSUE THREAD

**Issue by jiuwuxiaohun** [yansongda/laravel-pay#40]
只使用到了微信,用的是laravel-pay2.0.2

`[2019-08-26 10:32:31] local.ERROR: INVALID_ARGUMENT: Convert To Array Error! Invalid Xml! {"exception":"[object] (Yansongda\\Pay\\Exceptions\\InvalidArgumentException(code: 3): INVALID_ARGUMENT: Convert To Array Error! Invalid Xml! at /www/wwwroot/de.yqgxw.cn/vendor/yansongda/pay/src/Gateways/Wechat/Support.php:326)
[stacktrace]
#0 /www/wwwroot/de.yqgxw.cn/vendor/yansongda/pay/src/Gateways/Wechat.php(178): Yansongda\\Pay\\Gateways\\Wechat\\Support::fromXml('')
#1 /www/wwwroot/de.yqgxw.cn/app/Models/PrepaidRecord.php(138): Yansongda\\Pay\\Gateways\\Wechat->verify()
#2 /www/wwwroot/de.yqgxw.cn/app/Http/Controllers/Api/PayController.php(316): App\\Models\\PrepaidRecord::verify(1)
#3 [internal function]: App\\Http\\Controllers\\Api\\PayController->wxCcallBack()
#4 /www/wwwroot/de.yqgxw.cn/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#5 /www/wwwroot/de.yqgxw.cn/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('wxCcallBack', Array)
#6 /www/wwwroot/de.yqgxw.cn/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\Api\\PayController), 'wxCcallBack')
#7 /www/wwwroot/de.yqgxw.cn/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\\Routing\\Route->runController()
#8 /www/wwwroot/de.yqgxw.cn/vendor/laravel/framework/src/Illuminate/Routing/Router.php(682): Illuminate\\Routing\\Route->run()
#9 /www/wwwroot/de.yqgxw.cn/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#10 /www/wwwroot/de.yqgxw.cn/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#11 /www/wwwroot/de.yqgxw.cn/vendor/laravel/framework/src/Illuminate/Routing/Router.php(684): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#12 /www/wwwroot/de.yqgxw.cn/vendor/laravel/framework/src/Illuminate/Routing/Router.php(659): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#13 /www/wwwroot/de.yqgxw.cn/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#14 /www/wwwroot/de.yqgxw.cn/vendor/laravel/framework/src/Illuminate/Routing/Router.php(614): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))`

**Comment by yansongda** [comment]
麻烦 sdk 自带的 日志发一下

**Comment by nnnoml** [comment]
遇到同样的错误，自带日志返回 
`Received Wechat Request [""] `
应该是没有拿到报文
我用的是 hhxsv5/laravel-s

**Comment by nnnoml** [comment]
> 遇到同样的错误，自带日志返回
> `Received Wechat Request [""] `
> 应该是没有拿到报文
> 我用的是 hhxsv5/laravel-s

解决了，查看了源码verify可以传递参数 $pay->verify($request->getContent()) 这样xml就不报错了

**Comment by Captain1** [comment]
@nnnoml @yansongda
我也是没拿到报文，return_url都设置了，过来的整个$request打印出来都没看到有，支付宝没有问题，同步异步都OK
![wechat_cb](https://user-images.githubusercontent.com/4882809/69896717-83206700-137d-11ea-92d3-b9d70efe2188.jpg)

**Comment by binxyz** [comment]
我也是  INVALID_ARGUMENT: Convert To Array Error! Invalid Xml! 版本v2.8.6 ，不知道啥原因
