### ISSUE TITLE
laravel 5.8->6.0升级 提示 requires illuminate/support ^5.1 错误

### ISSUE THREAD

**Issue by sunjim** [yansongda/laravel-pay#41]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install laravel/framework v6.0.1
    - Conclusion: don't install laravel/framework v6.0.0
    - yansongda/laravel-pay v2.0.2 requires illuminate/support ^5.1

**Comment by yansongda** [comment]
是的，暂时还不支持 L6

晚些时候将进行适配，如果紧急，可以直接使用 yansongda/pay 进行代替

感谢支持
