### ISSUE TITLE
此模式下如何动态设置config?

### ISSUE THREAD

**Issue by jianglijs** [yansongda/laravel-pay#44]
我发现这样传Pay::alipay($this->config)的config不生效，还是从已配置的文件中读取

**Comment by jianglijs** [comment]
对php还是不是非常熟悉，希望可以得到解答。

**Comment by olivefm** [comment]
我也折腾了半天才发现不能传参数，详见：[#33](https://github.com/yansongda/laravel-pay/issues/33)
