### ISSUE TITLE
微信h5支付成功后，如何设置回调地址？

### ISSUE THREAD

**Issue by datangkang123** [yansongda/laravel-pay#45]
回调页面
正常流程用户支付完成后会返回至发起支付的页面，如需返回至指定页面，则可以在MWEB_URL后拼接上redirect_url参数，来指定回调页面。
这个怎么加？

**Comment by yansongda** [comment]
设置 return_url 即可

感谢支持

**Comment by datangkang123** [comment]
> return_url

return_url在哪设置呢？要修改源码吗？$order 里添加无效。

**Comment by datangkang123** [comment]
已经找到了，原来和支付宝一样，感谢了。
