### ISSUE TITLE
动态的传入config参数

### ISSUE THREAD

**Issue by algery** [yansongda/laravel-pay#6]
框架：lumen<br>
***
需求：动态的传入config参数<br>
***
详情：我的config参数不是固定的，需要动态的传入；我在文档中看到有这种写法
`$alipay = Pay::alipay($config)->web($order);`
所以我在使用时不新建config中的pay文件是否可以

**Comment by yansongda** [comment]
请问动态传参使用场景是哪方面呢？

您可以直接使用 yansongda/pay 这个包即可实现动态传参。

感谢您的支持。

**Comment by algery** [comment]
场景：web上支付与app上支付是两个应用；所以配置在pay.php中就无法满足

**Comment by yansongda** [comment]
那这个没办法了。确实是两个应用来的，一般也会放在不同的系统中。

**您可以直接使用 pay 这个包即可。**

如果这个场景多的话，我再考虑适配。

感谢支持

**Comment by algery** [comment]
好的。感谢回复。希望支持。

**Comment by admingalery** [comment]
这个场景应用应该还是多的，网页支付和App支付都会有。

**Comment by leo108** [comment]
测试环境和线上环境的 `notify_url` 和 `return_url` 是不一样的（至少域名是不一样的），而当初始化 config 的时候 Request 类还没初始化，因此 `url` 和 `route` 函数都无法使用。

下面这个配置是会报错的：

*config/pay.php*

```
 'notify_url' => route('payment.alipay.notify'),
 'return_url' => route('payment.alipay.return'),
```

>  In UrlGenerator.php line 102:
>  Type error: Argument 2 passed to Illuminate\Routing\UrlGenerator::__construct() must be an instance of Illuminate\Http\Request, null given, called in /home/vagrant/Code/laravel-shop/vendor/laravel/framework/src/Illuminate/Routing/RoutingServiceProvider.php on line 67

我认为一个比较合理的方案应该是：

```
Pay::alipay([
    'notify_url' => route('payment.alipay.notify'),
    'return_url' => route('payment.alipay.return'),
])
->web($order);
```

`alipay` 方法接受到的参数可以覆盖掉在 `config/pay.php` 的配置。
