### ISSUE TITLE
微信里没有WECHAT_APPID这个概念吧

### ISSUE THREAD

**Issue by gh372029002** [yansongda/laravel-pay#64]
WECHAT_APPID            APPID？
WECHAT_APP_ID          公证号ID
WECHAT_MINIAPP_ID   小程序ID

**Comment by puzzle9** [comment]
有没有都不重要了 得学会去看源码 然后给作者提轮子

**Comment by simon-8** [comment]
WECHAT_APPID 指的是开放平台的移动应用的APPID, 配置里有写注释的
