### ISSUE TITLE
laravel 支付宝回调post发送的数据接收为空

### ISSUE THREAD

**Issue by missTOTO** [yansongda/laravel-pay#68]
![微信图片_20210602095231](https://user-images.githubusercontent.com/33800689/120411952-42e1e080-c388-11eb-966b-a9a5c71c66bf.png)
在laravel6版本的框架中，支付宝支付回调发送的数据接收到打印出来的是空数组。我只能在控制器中使用$request->getContent()，格式化数据后传入verify()方法。

**Comment by yansongda** [comment]
如需要，可自行升级至最新 v3 beta 版本

感谢支持
