### ISSUE TITLE
服务器环境部署composer报错

### ISSUE THREAD

**Issue by yhs603** [yansongda/laravel-pay#83]
![image](https://user-images.githubusercontent.com/17921758/162911140-ac0ddbc3-79b7-47ed-9d21-f476137d30be.png)
PHP：7.4.14
laravel：8.83.2

**Comment by yhs603** [comment]
插件版本：3.0.3

**Comment by yansongda** [comment]
用 v3.1 版本吧，这个版本解决这个冲突了
