### ISSUE TITLE
请问应该如何在payserviceprodiver实现对pay::wechat(config(''pay))的绑定？

### ISSUE THREAD

**Issue by birdycn** [yansongda/laravel-pay#9]
您好，我是laravel新手，请问一下应该如何在

请问应该如何在payserviceprodiver实现对pay::wechat(config(''pay))的绑定？

**Comment by yansongda** [comment]
SDK 自动绑定了。不需要你操作。使用方法请看 readme 。

谢谢！

**Comment by birdycn** [comment]
@yansongda 
貌似大大理解错我的意思了，不过先问另一个问题：pay是不是只对参数做了处理，具体向微信发出的http请求还是需要自己处理？

然后我这个问题的意思是，就是每次调用pay::wechat($config)，都需要传入$config内容，我能不能做个服务注入？因为我是菜鸟，之前做的另一个例子是对 SMS::class 类注入，你这个是 pay::wechat方法，不知道应该怎么处理，网上文档貌似也不清晰
