### ISSUE TITLE
确认回调通知，返回给支付宝的success信息，前面多一个？号

### ISSUE THREAD

**Issue by tangyi90** [yansongda/laravel-pay#90]
这是用支付宝排查工具显示的信息

通知时间：2022-08-14 17:00:15

通知地址：保密

通知内容： 保密&notify_time=2022-08-14 17:00:15&subject=订单号：2022081404590339&sign=$$$&buyer_id=2088012453125342&invoice_amount=1.00&version=1.0&notify_id=2022081400222170014025341423947134&fund_bill_list=[{"amount":"1.00","fundChannel":"PCREDIT"}]&notify_type=trade_status_sync&out_trade_no=2022081404590339&total_amount=1.00&trade_status=TRADE_SUCCESS&trade_no=2022081422001425341448787155&auth_app_id=2017012205339646&receipt_amount=1.00&point_amount=0.00&buyer_pay_amount=1.00&app_id=2017012205339646&sign_type=RSA2&seller_id=2088102106367334	

**商户响应：http状态码: 200, 返回: ?success.**
**提示：返回值不是success**

返回值不是success前面多了一个？号

**Comment by yansongda** [comment]
看你自己代码里是不是多了

**Comment by tangyi90** [comment]
接到支付宝异步通知，我就返回你文档里面写的 return Pay::alipay()->success(); 没加其他东西

**Comment by yansongda** [comment]
去 yansongda/pay 里按 issue 格式提吧。

最好检查你自己的所有代码，99% 是你自己代码多了东西导致的
