### ISSUE TITLE
支付宝 app支付返回response实列，没返回参数？

### ISSUE THREAD

**Issue by vinwang** [yansongda/laravel-pay#91]
支付宝 app支付返回response实列，没返回参数
![image](https://user-images.githubusercontent.com/1687353/196400650-21a7dc39-815c-42a4-a5ad-44fe6db1dd82.png)

**Comment by yansongda** [comment]
看文档

**Comment by dogeow** [comment]
我粗略看了下，也是没看到在哪里。还得找。

**Comment by dogeow** [comment]
@vinwang ->getBody()->getContents();
