### ISSUE TITLE
Laravel-Pay在v3下使用Facades怎么使用多租户别名切换配置

### ISSUE THREAD

**Issue by asundust** [yansongda/laravel-pay#92]
`Yansongda\LaravelPay\Facades\Pay::wechat()->mp($order);`
貌似不支持别名去调用比如`Yansongda\LaravelPay\Facades\Pay::wechat('default')`或者`Yansongda\LaravelPay\Facades\Pay::wechat('config_name')`

**Comment by yansongda** [comment]
暂时不支持，如果有此类需求，可以直接使用  yansongda/pay
