### ISSUE TITLE
大佬请问laravel门面方式怎么动态传入商户配置？

### ISSUE THREAD

**Issue by nfhh** [yansongda/laravel-pay#96]
use Pay;

$order = [
    'out_trade_no' => time(),
    'total_amount' => '1',
    'subject' => 'test subject - 测试',
];

return Pay::alipay(这里传入$config好像不行)->web($order); // 因为我的配置信息是存在mysql表里，我想查出就传入

// 下面这个方法也可以
// return Pay::web($order);

**Comment by yansongda** [comment]
动态使用 [yansongda/pay](https://github.com/yansongda/pay)

**Comment by nfhh** [comment]
你的意思如果要动态就不能用门面方式了么？
